export default [
  "(Pay no attention to the man behind the curtain)",
  "You're not in Kansas any more.",
  "Moving satellite into position...",
  "I should have had a V8 this morning.",
  "My other loading screen is much faster.",
  "Do not run! We are your friends!",
  "Do you come here often?",
  "Loading the enchanted bunny...",
  "I'm sorry Dave, I can't do that.",
  "All your web browser are belong to us",
  "I feel like im supposed to be loading something...",
  "What do you call 8 Hobbits? A Hobbyte.",
  "Should have used a compiled language...",
  "Unicorns are at the end of this road, I promise.",
  "Putting the icing on the cake. The cake is not a lie...",
  "99 bottles of beer on the wall..",
  "You shall not pass! yet..",
  "Load it and they will come.",
  "There is no spoon. Because we are not done loading it.",
  "Wait, do you smell something burning?",
  "When nothing is going right, go left!!...",
  "I think I am, therefore, I am. I think.",
  "A commit a day keeps the mobs away.",
  "Constructing additional pylons...",
  "Roping some seaturtles...",
  "Locating Jebediah Kerman...",
  "Well, this is embarrassing.",
  "I'm going to walk the dog.",
  "I didn't choose the engineering life. The engineering life chose me.",
  "We’re going to need a bigger boat.",
  "Simulating traveling salesman...",
  "Twiddling thumbs...",
  "Searching for plot device...",
  "Trying to sort in O(n)...",
  "Sending data to NS.. I mean, our servers...",
  "Looking for sense of humour, please hold on.",
  "A different error message? Finally, some progress!",
  "Hold on while we wrap up our git together...sorry",
  "Winter is coming...",
  "Installing dependencies",
  "Switching to the latest JS framework...",
  "Distracted by cat gifs",
  "Ordering 1s and 0s...",
  "It is dark. You're likely to be eaten by a grue.",
  "Loading funny message...",
  "It's 10:00pm. Do you know where your children are?",
  "What's under there?",
  "Help, I'm trapped in a loader!",
  "Downloading more RAM..",
  "Initializing the initializer...",
  "Last call for the data bus! All aboard!",
  "Running swag sticker detection...",
  "Never let a computer know you're in a hurry.",
  "Shovelling coal into the server...",
  "Pushing pixels...",
  "How about this weather, eh?",
  "Building a wall...",
  "Everything in this universe is either a potato or not a potato",
  "Debugging Debugger...",
  "Running with scissors...",
  "Definitely not a virus...",
  "You may call me Steve.",
  "Coffee at my place, tommorow at 10A.M. - don't be late!",
  "Work, work...",
  "Time flies like an arrow; fruit flies like a banana",
  "Two men walked into a bar; the third ducked...",
  "Sorry, we're busy catching em' all. We'll be done soon",
  "TODO: Insert elevator music",
  "Please wait while the minions do their work",
  "You are number 2843684714 in the queue",
  "Please wait while we serve other customers...",
  "Our premium plan is faster",
  "Feeding unicorns...",
  "Up, Up, Down, Down, Left, Right, Left, Right, B, A.",
  "Do you like my loading animation? I made it myself.",
  "Whoah, look at it go!",
  "No, I'm awake. I was just resting my eyes.",
  "One mississippi, two mississippi...",
  "Don't panic... AHHHHH!",
  "Ensuring Gnomes are still short.",
  "We apologize for the wait. Those responsible for the wait have been sacked.",
  "Deploying deadly neurotoxins...",
  "These are not the droids you're looking for...",
  "Let's take a moment to reflect on what we are doing here...",
  "Computing the secret to life, the universe, and everything...",
  "Locating the required gigapixels to render...",
  "Shhhhh! I'm thinking...",
  "Digesting cookies... nom nom nom...",
  "Breaking out of the time loop. Please wait...",
  "Preparing for hyperspace jump...",
  "My other computer is an abacus.",
  "In case of AI uprising, stand still.",
];